### ISSUE TITLE
API NIC.ru

### ISSUE THREAD

**Issue by wolfktl** [shizacat/certbot-dns-nicru#2]
dns_nicru_client_id = application-id 
dns_nicru_client_secret = application-token
dns_nicru_username = 0001110/NIC-D
dns_nicru_password = password

dns_nicru_scope = .+:.+/zones/example.com(/.+)?

dns_nicru_service = DNS_SERVICE_NAME
dns_nicru_zone = example.com

application-id  и application-token получаем после регистрации приложения OAuth 2.0  ? 
что за DNS_SERVICE_NAME ?

**Comment by shizacat** [comment]
> application-id и application-token получаем после регистрации приложения OAuth 2.0 ?

Все верно

> что за DNS_SERVICE_NAME ?

Это название услуги, оно задается при подключение 'DNS хостинга'. Так же можно посмотреть в разделе - 'DNS-хостинг', будет табличка и в столбце услуга будет ее название.

**Comment by wolfktl** [comment]
Спасибо. То что-тог нужно. Сертификат генерит при запуске контейнера? его надо запускать каждый раз? или он сам будет генерит сертификат по мере необходимости?
